const mongoose = require('mongoose');

// A LeadActivity is a single touchpoint logged against a Lead on a specific date.
// Multiple activities can be logged per lead per day.

const leadActivitySchema = new mongoose.Schema({
  leadId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Lead',
    required: true
  },
  adminId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  date: {
    type: Date,
    required: true
  },
  channel: {
    type: String,
    enum: ['cold-call', 'linkedin', 'whatsapp', 'event', 'referral', 'email', 'meeting', 'other'],
    default: 'other'
  },
  outcome: {
    type: String,
    enum: ['interested', 'follow-up', 'not-interested', 'no-response', 'meeting-set', 'proposal-sent', 'closed'],
    default: 'no-response'
  },
  note: {
    type: String,
    trim: true,
    maxlength: 500,
    default: ''
  },
  // optional: stage changed to this after this activity
  stageAfter: {
    type: String,
    enum: ['lead', 'conversation', 'meeting', 'proposal', 'client', 'lost', ''],
    default: ''
  },
  // true = auto-generated by system on lead update, false = manually logged
  isSystemLog: {
    type: Boolean,
    default: false
  }
}, {
  timestamps: true
});

leadActivitySchema.index({ leadId: 1, date: -1 });
leadActivitySchema.index({ adminId: 1, date: 1 });

module.exports = mongoose.model('LeadActivity', leadActivitySchema);
